<?php

namespace AppBundle\Repository;

/**
 * DummyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DummyRepository extends \Doctrine\ORM\EntityRepository
{
}
